Add missing dep for reco::Candidate, reco::TrackBase
Resolves linking errors:

    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0x98): undefined reference to peinfo for reco::Candidate'
    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0xd8): undefined reference to peinfo for reco::Candidate'
    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0x118): undefined reference to peinfo for reco::Candidate'
    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0x158): undefined reference to peinfo for reco::Candidate'
    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0x198): undefined reference to peinfo for reco::Candidate'
    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0x1d8): more undefined references to peinfo for reco::Candidate' follow
    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0x298): undefined reference to peinfo for reco::TrackBase'
    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0x458): undefined reference to peinfo for reco::TrackBase'
    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0x498): undefined reference to peinfo for reco::TrackBase'
    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0x4d8): undefined reference to peinfo for reco::TrackBase'
    PhysicsToolsJetCharge/JetCharge.o:(.data.rel+0x518): undefined reference to peinfo for reco::TrackBase'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>