Add missing dep for CaloCellGeometry, CaloSubdetectorTopology
Resolves linking errors:

    RecoParticleFlowPFClusterShapeProducer/PFClusterShapeAlgo.o:(.data.rel+0x558): undefined reference to peinfo for CaloCellGeometry'
    RecoParticleFlowPFClusterShapeProducer/PFClusterShapeAlgo.o:(.data.rel+0x658): undefined reference to peinfo for CaloSubdetectorTopology'
    RecoParticleFlowPFClusterShapeProducer/PFClusterShapeAlgo.o:(.data.rel+0x698): undefined reference to peinfo for CaloSubdetectorTopology'
    RecoParticleFlowPFClusterShapeProducer/PFClusterShapeAlgo.o:(.data.rel+0x6d8): undefined reference to peinfo for CaloSubdetectorTopology'
    RecoParticleFlowPFClusterShapeProducer/PFClusterShapeAlgo.o:(.data.rel+0x718): undefined reference to peinfo for CaloSubdetectorTopology'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>