GEMCSCSegAlgoRR: initialize xe and ye
    DataFormats/GeometryVector/interface/extBasic3DVector.h:78:14: error:
    'ye' may be used uninitialized in this function
    [-Werror=maybe-uninitialized]
         v{x,y,z,w}{}
              ^
    RecoLocalMuon/GEMCSCSegment/plugins/GEMCSCSegAlgoRR.cc:217:14: note:
    'ye' was declared here
        float xe, ye, ze = 0.0;

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>