Remove shared_ptr support from EOS Portable Archive
`boost::archive::detail::shared_ptr_helper` has been replaced by
`boost::serialization::shared_ptr_helper`. Thus `shared_ptr_helper`
ctor/dtor symbols are missing from Boost Serialization library.

    undefined reference to `boost::archive::detail::shared_ptr_helper
    ::shared_ptr_helper()'
    undefined reference to `boost::archive::detail::shared_ptr_helper
    ::~shared_ptr_helper()'

The new `shared_ptr_helper` implementation is in
`shared_ptr_helper.cpp`, but the file is not listes in `SOURCES` in
`libs/serialization/build/Jamfile.v2`.

Adding it would break Boost Serialization.

`boost::archive::detail::shared_ptr_helper` is valid until 1.55.0
(incl.). The patch hardcodes this fact, meaning that 1.56.0+ will not
have `shared_ptr` support.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>