Add missing <cmath> include; use std::fabs
Tested with GCC 6.0.0 (r234661):

    DQMOffline/JetMET/interface/SusyDQM/HT.h:38:42: error: call of overloaded 'abs(double)' is ambiguous

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>