SIMDVec: enable USE_SSEVECT for __INTEL_COMPILER
There are no record why this was disabled on ICC. Thus ICC was using
`oldBasic3DVector.h`, but it's not compile with SSE and EXT
implementation thus causing build errors in
RecoParticleFlow/PFClusterTools:

    RecoParticleFlow/PFClusterTools/src/LinkByRecHit.cc(9): error: class
    "Basic2DVector<double>" has no member "v"

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>