Add missing <cassert> header
The following errors are reported by GCC (6.0.0, r233941):

    SimCalorimetry/HcalSimAlgos/src/HcalSiPM.cc:105:18: error: 'assert' was not declared in this scope
    SimCalorimetry/HcalSimAlgos/src/HcalSiPM.cc:15:24: error: 'assert' was not declared in this scope

Patch adds the missing header.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>