Use std::abs for enum (tauImpactParameter::PDGInfo::PDGMCNumbering)
The following errors are reported by GCC (6.0.0, r233941):

    RecoTauTag/ImpactParameter/src/TauA1NuConstrainedFitter.cc:179:98: error: call of overloaded 'fabs(tauImpactParameter::PDGInfo::PDGMCNumbering)' is ambiguous

Include missing <cmath> header, add std:: where needed and change
std::fabs to std::abs for int type (enum, PDGInfo::PDGMCNumbering).

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>