Resolve errors where address is used in if-statement
The path resolves the following errors:

    error: address of 'this->triggerResults_' will always evaluate to
    'true' [-Werror,-Wpointer-bool-conversion]

Taking an address of `triggerResults_` and implicitly converting to bool
will always yield true.

I believe author wanted `triggerResults_.isValid()`.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>