Add missing <numeric> include for std::accumulate
The following errors are reported by GCC (6.0.0, r233941):

    RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc:553:20: error: 'accumulate' is not a member of 'std'
    RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc:2055:30: error: 'accumulate' is not a member of 'std'
    RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc:2308:22: error: 'accumulate' is not a member of 'std'
    RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc:2310:22: error: 'accumulate' is not a member of 'std'

    RecoParticleFlow/PFClusterTools/src/PFEnergyCalibration.cc:392:15: error: 'accumulate' is not a member of 'std'
    RecoParticleFlow/PFClusterTools/src/PFEnergyCalibration.cc:393:15: error: 'accumulate' is not a member of 'std'
    RecoParticleFlow/PFClusterTools/src/PFEnergyCalibration.cc:419:15: error: 'accumulate' is not a member of 'std'
    RecoParticleFlow/PFClusterTools/src/PFEnergyCalibration.cc:420:15: error: 'accumulate' is not a member of 'std'

    RecoJets/JetProducers/plugins/QjetsAdder.cc:77:19: error: 'accumulate' is not a member of 'std'

Patch add the missing <numeric> include.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>