Add missing HcalDeterministicFit::rCorrSiPM
The following error in blocking Clang builds:

    RecoLocalCaloHcalRecAlgos/HcalDeterministicFit.o: In function calDeterministicFit::phase1Apply(HBHEChannelInfo const&, float&, float&) const':
    RecoLocalCalo/HcalRecAlgos/src/HcalDeterministicFit.cc:(.text+0x583): undefined reference to calDeterministicFit::rCorrSiPM'
    RecoLocalCalo/HcalRecAlgos/src/HcalDeterministicFit.cc:(.text+0x5a9): undefined reference to calDeterministicFit::rCorrSiPM'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>