Add missing dependency for TkAccumulatingSensitiveDetector
Resolves linking errors:

    LaserAlignmentSimulationPlugins/LaserAlignmentSimulation.o:(.data.rel+0x23d8): undefined reference to peinfo for TkAccumulatingSensitiveDetector'
    LaserAlignmentSimulationPlugins/LaserAlignmentSimulation.o:(.data.rel+0x2418): undefined reference to peinfo for TkAccumulatingSensitiveDetector'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>