PhysicsTools/IsolationAlgos: add missing dependecy on DataFormats/PatCandidates
The plugin is failing to build on CMSSW_7_5_X/AArch64:

    PhysicsToolsIsolationAlgos_plugins/CITKPFIsolationSumProducer.o: In function 'citk::PFIsolationSumProducer::produce(edm::Event&, edm::EventSetup const&)':
    CITKPFIsolationSumProducer.cc:(.text+0x186c): undefined reference to 'pat::PackedCandidate::unpack() const'
    PhysicsToolsIsolationAlgos_plugins/CITKPFIsolationSumProducer.o: In function 'pat::PackedCandidate::pt() const':
    CITKPFIsolationSumProducer.cc:(.text._ZNK3pat15PackedCandidate2ptEv[_ZNK3pat15PackedCandidate2ptEv]+0x18): undefined reference to 'pat::PackedCandidate::unpack() const'

According to LXR `pat::PackedCandidate` is used in 3 files.

http://cmslxr.fnal.gov/ident?v=CMSSW_7_5_X_2015-06-02-2300&_i=PackedCandidate&_remember=1

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>