Add missing <cmath> header or/and std::
The following errors are reported by GCC (6.0.0, r233941):

    L1Trigger/L1TMuonOverlap/src/OMTFSorter.cc:162:38: error: call of overloaded 'abs(float)' is ambiguous

    L1Trigger/L1TMuonBarrel/src/Twinmux_v1/PrimitiveCombiner.h:83:78: error: call of overloaded 'abs(float)' is ambiguous

    EventFilter/L1TRawToDigi/src/Unpacker.cc:14:28: error: 'floor' was not declared in this scope

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>