Resolve errors where address is used in if-statement
The patch resolves the following error:

    error: address of 'this->m_triggerResults' will
    always evaluate to 'true'

Taking an address of `triggerResults_` and implicitly converting to bool
will always yield true.

I believe author wanted `triggerResults_.isValid()`.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>