Add missing dep for edm::EventBase
Resolves linking errors:

    PhysicsToolsUtilities/LumiReWeighting.o:(.data.rel+0x1d8): undefined reference to peinfo for edm::EventBase'
    PhysicsToolsUtilities/LumiReWeighting.o:(.data.rel+0x218): undefined reference to peinfo for edm::EventBase'
    PhysicsToolsUtilities/LumiReWeighting.o:(.data.rel+0x258): undefined reference to peinfo for edm::EventBase'
    PhysicsToolsUtilities/LumiReWeighting.o:(.data.rel+0x398): undefined reference to peinfo for edm::EventBase'
    PhysicsToolsUtilities/LumiReWeighting.o:(.data.rel+0x3d8): undefined reference to peinfo for edm::EventBase'
    PhysicsToolsUtilities/Lumi3DReWeighting.o:(.data.rel+0x1b98): more undefined references to peinfo for edm::EventBase' follow

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>