Resolve missing-braces error
    ExtVec.h:218:3: error: missing braces around initializer for
    'Rot3<float>::Vec {aka __vector(4) float}' [-Werror=missing-braces]
    ExtVec.h:218:3: error: missing braces around initializer for
    'Rot3<double>::Vec {aka __vector(4) double}' [-Werror=missing-braces]

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>