Add missing dep for ForwardDetLayer, BarrelDetLayer, GeometricSearchTracker
Resolves linking errors:

    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x6258): undefined reference to peinfo for ForwardDetLayer'
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x6358): undefined reference to peinfo for ForwardDetLayer'
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x63d8): undefined reference to peinfo for ForwardDetLayer'
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x64d8): undefined reference to peinfo for ForwardDetLayer'
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x6558): undefined reference to peinfo for ForwardDetLayer'
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x6658): more undefined references to peinfo for ForwardDetLayer' follow
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x77d8): undefined reference to peinfo for BarrelDetLayer'
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x78d8): undefined reference to peinfo for BarrelDetLayer'
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x79d8): undefined reference to peinfo for BarrelDetLayer'
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x7ad8): undefined reference to peinfo for BarrelDetLayer'
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x7bd8): undefined reference to peinfo for BarrelDetLayer'
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x7cd8): more undefined references to peinfo for BarrelDetLayer' follow
    FastSimulationTrackerSetup/TrackerInteractionGeometry.o:(.data.rel+0x84d8): undefined reference to peinfo for GeometricSearchTracker'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>