Add missing dependency for HcalGeometry
Resolves linking errors:

    testGeometryCaloTowerMap/CaloTowerMapTester.o:(.data.rel+0x2a18): undefined reference to peinfo for HcalGeometry'
    testGeometryCaloTowerMap/CaloTowerMapTester.o:(.data.rel+0x2a58): undefined reference to peinfo for HcalGeometry'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>