Add missing dependency for reco::TrackBase
Resolves linking errors:

    PhysicsToolsParallelAnalysis/TrackAnalysisAlgorithm.o:(.data.rel+0x758): undefined reference to peinfo for reco::TrackBase'
    PhysicsToolsParallelAnalysis/TrackAnalysisAlgorithm.o:(.data.rel+0x7d8): undefined reference to peinfo for reco::TrackBase'
    PhysicsToolsParallelAnalysis/TrackAnalysisAlgorithm.o:(.data.rel+0x858): undefined reference to peinfo for reco::TrackBase'
    PhysicsToolsParallelAnalysis/TrackAnalysisAlgorithm.o:(.data.rel+0x8d8): undefined reference to peinfo for reco::TrackBase'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>