Add missing headers (GCC 6.0.0)
The following errors are reported by GCC (6.0.0, r233941):

    HLTrigger/JetMET/src/AlphaT.cc:21:25: error: 'accumulate' is not a member of 'std'
    HLTrigger/JetMET/src/AlphaT.cc:22:25: error: 'accumulate' is not a member of 'std'
    HLTrigger/JetMET/src/AlphaT.cc:23:25: error: 'accumulate' is not a member of 'std'
    HLTrigger/JetMET/src/AlphaT.cc:39:43: error: call of overloaded 'abs(double&)' is ambiguous
    HLTrigger/JetMET/src/AlphaT.cc:50:99: error: 'sqrt' was not declared in this scope

Patch adds missing headers and adds `std::` where needed.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>