Add missing dep for reco::GenParticle, reco::LeafCandidate
Resolves linking errors:

    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x18): undefined reference to peinfo for reco::GenParticle'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0xd8): undefined reference to peinfo for reco::LeafCandidate'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x118): undefined reference to peinfo for reco::GenParticle'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x1d8): undefined reference to peinfo for reco::LeafCandidate'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x218): undefined reference to peinfo for reco::GenParticle'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x418): undefined reference to peinfo for reco::LeafCandidate'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x458): undefined reference to peinfo for reco::GenParticle'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x498): undefined reference to peinfo for reco::Candidate'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x4d8): undefined reference to peinfo for reco::GenParticle'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x518): undefined reference to peinfo for reco::GenParticle'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x558): undefined reference to peinfo for reco::Candidate'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x598): undefined reference to peinfo for reco::LeafCandidate'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x658): undefined reference to peinfo for reco::Candidate'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x698): undefined reference to peinfo for reco::Candidate'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x6d8): undefined reference to peinfo for reco::LeafCandidate'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x798): undefined reference to peinfo for reco::GenParticle'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel+0x858): undefined reference to peinfo for reco::LeafCandidate'
    ValidationEventGenerator/TauDecay_GenParticle.o:(.data.rel.ro._ZTIN4reco22CompositeRefCandidateTIN3edm9RefVectorISt6vectorINS_11GenParticleESaIS4_EES4_NS1_9refhelper16FindUsingAdvanceIS6_S4_EEEEEE[_ZTIN4reco22CompositeRefCandidateTIN3edm9RefVectorISt6vectorINS_11GenParticleESaIS4_EES4_NS1_9refhelper16FindUsingAdvanceIS6_S4_EEEEEE]+0x10): undefined reference to peinfo for reco::LeafCandidate'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>