Resolve unused variable 'SECS_PER_LUMI' error
Clang 3.5.0 complains regarding unused variable:

    DQM/HLTEvF/plugins/TriggerRatesMonitor.cc:44:21: error: unused variable
    'SECS_PER_LUMI' [-Werror,-Wunused-const-variable]

The patch removes it.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>