Changes to make RISCV64 complaint
It was creating this crash:
  File "/cvmfs/cms-ib.cern.ch/sw/riscv64/nweek-02949/fc42_riscv64_gcc15/cms/cmssw/CMSSW_20_1_X_2026-07-09-2300/src/Configuration/EventContent/python/EventContent_cff.py", line 994, in <module>
    from PhysicsTools.PatAlgos.slimming.slimming_cff import MicroEventContent,MicroEventContentMC,MicroEventContentGEN
  File "/cvmfs/cms-ib.cern.ch/sw/riscv64/nweek-02949/fc42_riscv64_gcc15/cms/cmssw/CMSSW_20_1_X_2026-07-09-2300/src/PhysicsTools/PatAlgos/python/slimming/slimming_cff.py", line 3, in <module>
    from PhysicsTools.PatAlgos.slimming.packedPFCandidates_cff import *
  File "/cvmfs/cms-ib.cern.ch/sw/riscv64/nweek-02949/fc42_riscv64_gcc15/cms/cmssw/CMSSW_20_1_X_2026-07-09-2300/src/PhysicsTools/PatAlgos/python/slimming/packedPFCandidates_cff.py", line 5, in <module>
    from CommonTools.ParticleFlow.PFBRECO_cff import pfPileUpPFBRECO, pfNoPileUpPFBRECO
  File "/cvmfs/cms-ib.cern.ch/sw/riscv64/nweek-02949/fc42_riscv64_gcc15/cms/cmssw/CMSSW_20_1_X_2026-07-09-2300/src/CommonTools/ParticleFlow/python/PFBRECO_cff.py", line 4, in <module>
    from RecoParticleFlow.PFProducer.pfLinker_cff import particleFlowPtrs
  File "/cvmfs/cms-ib.cern.ch/sw/riscv64/nweek-02949/fc42_riscv64_gcc15/cms/cmssw/CMSSW_20_1_X_2026-07-09-2300/src/RecoParticleFlow/PFProducer/python/pfLinker_cff.py", line 3, in <module>
    import RecoParticleFlow.PFProducer.pfLinker_cfi
ModuleNotFoundError: No module named 'RecoParticleFlow.PFProducer.pfLinker_cfi'