correctedP4 must return a copy of p4()
`correctedJet()` returns a new `Jet` object. In `correctedP4()` we
return a reference to p4() on a stack, thus the reference is invalid and
most likely value will be changed with the next few function calls.

    DataFormats/PatCandidates/interface/Jet.h:155:178: error: function
    returns address of local variable [-Werror=return-local-addr]
    DataFormats/PatCandidates/interface/Jet.h:158:204: error: function
    returns address of local variable [-Werror=return-local-addr]

A quick fix (this patch) is to make `correctedP4()` return a copy
instead of a reference.

If `correctedJet()` is on hot path, the new `Jet` object should be
cached and then we could also return a reference in `correctedP4()`.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>