Add missing dependency for SteppingAction
Resolves linking error:

SimG4CoreGFlash/GflashHadronShowerModel.o:(.data.rel+0xd18): undefined reference to peinfo for SteppingAction'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>