CalibCalorimetry/CaloTPG: definite static constexpr float members
The patch resolves issue with Clang compiler.
N3690 (should be C++11 standard) and latest draft N4567, 9.4.2/3

...
The member shall still be defined in a namespace scope if it
is odr-used (3.2) in the program and the namespace scope definition
shall not contain an initializer.
9.4.2/4 talks about how const static data members are being handled.

Also standard says that no diagnostic is required by compiler.

    src/CalibCalorimetryCaloTPG/CaloTPGTranscoderULUT.o: In function aloTPGTranscoderULUT::setup(HcalLutMetadata const&, HcalTrigTowerGeometry const&)':
    src/CalibCalorimetry/CaloTPG/src/CaloTPGTranscoderULUT.cc:(.text+0x168b): undefined reference to aloTPGTranscoderULUT::LSB_HBHE'
    src/CalibCalorimetry/CaloTPG/src/CaloTPGTranscoderULUT.cc:(.text+0x16b6): undefined reference to aloTPGTranscoderULUT::LSB_HF'

Before:

    $ nm -a ../lib/slc6_amd64_gcc493/libCalibCalorimetryCaloTPG.so | wc -l
    153

After:

    $ nm -a ../lib/slc6_amd64_gcc493/libCalibCalorimetryCaloTPG.so | wc -l
    155

    $ nm -a ../lib/slc6_amd64_gcc493/libCalibCalorimetryCaloTPG.so | c++filt | grep -E '(LSB_HF|LSB_HBHE)'
    000000000000871c R CaloTPGTranscoderULUT::LSB_HF
    0000000000008718 R CaloTPGTranscoderULUT::LSB_HBHE

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>
(cherry picked from commit b430d19d3a6f7176b97bd4fe4cd2e58fa4432598)