c_str() returns const char * and return of strstr() must be const char * as const char * strstr ( const char * str1, const char * str2 ) prototype is used.
The following changes fix compilation errors on SLC6 GCC 4.6.2 machines:
error: invalid conversion from 'const char*' to 'char*'