Utilities/XrdAdaptor: fix -Wunused-result errors
Some xrootd methods are marked with `XRD_WARN_UNUSED_RESULT`
(`__attribute__((warn_unused_result))`) and `-Wunused-result` forces us
to not ignore return values.

    src/Utilities/XrdAdaptor/src/XrdSource.cc:327:9: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
    src/Utilities/XrdAdaptor/src/XrdSource.cc:338:9: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
    src/Utilities/XrdAdaptor/src/XrdRequestManager.cc:102:9: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
    src/Utilities/XrdAdaptor/plugins/XrdStorageMaker.cc:86:5: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>
(cherry picked from commit 7134e880d0e312bba9eb4d915fb01aeaeb694a80)