Clean where address is used as a pointer
Address is not a pointer, thus comparing it to a 0/NULL/nullptr does not
make sense -- it's always false. Compiler can assume that address is
never 0/NULL/nullptr.

Tested with GCC 6.0.0 (r234661):

    DQM/CSCMonitorModule/plugins/CSCDQM_EventProcessor_processCSC.cc:87:15: error: the compiler can assume that the address of 'data' will never be NULL [-Werror=address]
    DQMOffline/JetMET/src/HTMHTAnalyzer.cc:85:21: error: the compiler can assume that the address of 'triggerResults' will always evaluate to 'true' [-Werror=address]
    DQMOffline/PFTau/src/Benchmark.cc:25:10: error: the compiler can assume that the address of 'b' will always evaluate to 'true' [-Werror=address]
    DQMOffline/PFTau/src/Benchmark.cc:35:10: error: the compiler can assume that the address of 'b' will always evaluate to 'true' [-Werror=address]
    DQMOffline/PFTau/src/Benchmark.cc:45:10: error: the compiler can assume that the address of 'b' will always evaluate to 'true' [-Werror=address]
    DQMOffline/PFTau/src/Benchmark.cc:63:10: error: the compiler can assume that the address of 'b' will always evaluate to 'true' [-Werror=address]
    DQMOffline/PFTau/src/Benchmark.cc:80:10: error: the compiler can assume that the address of 'b' will always evaluate to 'true' [-Werror=address]
    DQM/Physics/src/EwkMuLumiMonitorDQM.cc:359:14: error: the compiler can assume that the address of 'toc' will never be NULL [-Werror=address]
    DQM/SiStripCommissioningSummary/src/DaqScopeModeSummaryFactory.cc:91:24: error: the compiler can assume that the address of 'summary_histo' will always evaluate to 'true' [-Werror=address]
    DQM/SiStripCommissioningSummary/src/FedTimingSummaryFactory.cc:108:24: error: the compiler can assume that the address of 'summary_histo' will always evaluate to 'true' [-Werror=address]
    DQM/SiStripCommissioningSummary/src/SummaryHistogramFactory.cc:103:8: error: the compiler can assume that the address of 'summary_histo' will always evaluate to 'true' [-Werror=address]
    DQM/SiStripCommissioningSummary/src/SummaryPlotFactoryBase.cc:131:24: error: the compiler can assume that the address of 'summary_histo' will always evaluate to 'true' [-Werror=address]

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>