Add dependency for missing CaloHitID and CaloG4Hit
Resolves linking errors:

    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0x4d8): undefined reference to peinfo for CaloHitID'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0x558): undefined reference to peinfo for CaloG4Hit'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0x6d8): undefined reference to peinfo for CaloG4Hit'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0x718): undefined reference to peinfo for CaloG4Hit'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0x758): undefined reference to peinfo for CaloG4Hit'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0x7d8): undefined reference to peinfo for CaloHitID'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0x818): undefined reference to peinfo for CaloG4Hit'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0x858): undefined reference to peinfo for CaloHitID'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0x8d8): undefined reference to peinfo for CaloG4Hit'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0xa58): undefined reference to peinfo for CaloHitID'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0xa98): undefined reference to peinfo for CaloG4Hit'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0xad8): undefined reference to peinfo for CaloHitID'
    ValidationEcalHits/EcalSimHitsValidProducer.o:(.data.rel+0xb58): undefined reference to peinfo for CaloG4Hit'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>