Add missing dependency for CaloCellGeometry
Resolves linking error:

    DataFormatsParticleFlowReco/PFRecHit.o:(.data.rel+0xd8): undefined reference to peinfo for CaloCellGeometry'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>